"""Configuration schema for resource management settings including GPU thresholds"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/management_config.ipynb.

# %% auto 0
__all__ = ['RESOURCE_MANAGEMENT_SCHEMA']

# %% ../../nbs/core/management_config.ipynb 4
# Resource management configuration schema
RESOURCE_MANAGEMENT_SCHEMA = {
    "type": "object",
    "name": "resource-management",
    "title": "Resource Management Configuration",
    "menu_title": "Resource Management",
    "description": "Configure resource usage thresholds and conflict detection",
    "properties": {
        "gpu_memory_threshold_percent": {
            "type": "number",
            "title": "GPU Memory Threshold (%)",
            "description": "External processes using more than this percentage of GPU memory are considered conflicts",
            "minimum": 1,
            "maximum": 99,
            "default": 35.0
        },
        "enable_auto_unload": {
            "type": "boolean",
            "title": "Auto-Unload Idle Models",
            "description": "Automatically unload idle models when switching to a different plugin",
            "default": True
        },
        "enable_auto_reload": {
            "type": "boolean",
            "title": "Auto-Reload Models",
            "description": "Automatically reload models when configuration changes",
            "default": True
        }
    },
    "required": []
}
